name: Build Outdoor.sy

on: [push, pull_request]

jobs:
  ruby:
    runs-on: ubuntu-latest
    working-directory: ruby
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: "3.1.2"
          bundler-cache: true
      - name: rubocop
        run: bundle exec rubocop
      - name: rspec
        run: bundle exec rspec

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go-version }}
      - name: vet
        run: go vet ./...
      - name: fmt
        run: test -z $(gofmt -l .)

  test:
    needs: [lint]
    strategy:
      matrix:
        go-version: ["1.18.x", "1.19.x"]
        os: ["ubuntu-latest", "macos-latest", "windows-latest"]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go-version }}
      - name: build
        run: go build ./...
      - name: unit tests
        run: go test ./... -v

  build:
    needs: [test]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: "1.19"
      - name: build
        run: ./crossarch_builds.sh
      - name: Archive binaries
        uses: actions/upload-artifact@v3
        with:
          name: outdoorsy binaries
          path: bin
