name: Build Outdoor.sy

on: [push]

jobs:
  build:
    strategy:
      matrix:
        go-version: ["1.18.x", "1.19.x"]
        os: ["ubuntu-latest", "macos-latest", "windows-latest"]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go-version }}
      - name: unit tests
        run: go test ./... -v
      - name: build
        run: go build ./...
